# Copyright (c) 2026 Andre Jacobs
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: ajfs

before:
    hooks:
        - go mod tidy
        #- go generate ./...

builds:
    - env:
          - CGO_ENABLED=0
      goos:
          - linux
          - windows
          - darwin
      main: ./cmd/ajfs
      ldflags:
          - -s -w
          - -X github.com/andrejacobs/go-aj/buildinfo.AppName={{.ProjectName}}
          - -X github.com/andrejacobs/go-aj/buildinfo.Version={{.Version}}
          - -X github.com/andrejacobs/go-aj/buildinfo.GitCommitHash={{.FullCommit}}

archives:
    - formats: [tar.gz]
      # this name template makes the OS and Arch compatible with the results of `uname`.
      name_template: >-
          {{ .ProjectName }}_
          {{- title .Os }}_
          {{- if eq .Arch "amd64" }}x86_64
          {{- else if eq .Arch "386" }}i386
          {{- else }}{{ .Arch }}{{ end }}
          {{- if .Arm }}v{{ .Arm }}{{ end }}
      # use zip for windows archives
      format_overrides:
          - goos: windows
            formats: [zip]

changelog:
    sort: asc
    filters:
        exclude:
            - "^docs:"
            - "^test:"

release:
    footer: >-

        ---

        Released by [GoReleaser](https://github.com/goreleaser/goreleaser).
